version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "browser",
    "nodejs"
  ]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Olimi-org/Afterpiece"

[[analyzers]]
name = "shell"
